dist: xenial
language: cpp
compiler: clang
env:
  - TARGET=helloworld VERSION=0.0.${TRAVIS_BUILD_NUMBER}
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- ./${TARGET}
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T *.deb -usild:${BINTRAY_API_KEY} "https://api.bintray.com/content/sild/otus-cpp/homework/${VERSION}/${TARGET}-${VERSION}-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
