dist: xenial
language: cpp
compiler: clang
env:
  - TARGET=matrix
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
      curl -T ${TARGET}-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb -usild:${BINTRAY_API_KEY} "https://api.bintray.com/content/sild/otus-cpp/homework/0.0.${TRAVIS_BUILD_NUMBER}/${TARGET}-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

