dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    sources:
    - llvm-toolchain-xenial-7
    packages:
    - libc++-7-dev
    - libc++abi-7-dev
    - doxygen
    - graphviz
    update: true
env:
  - TARGET=print_ip
script:
- CXXFLAGS="-stdlib=libc++" cmake .
- cmake --build .
- cmake --build . --target package
- doxygen Doxyfile
deploy:
  - provider: script
    skip_cleanup: true
    script:
      curl -T ${TARGET}-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb -usild:${BINTRAY_API_KEY} "https://api.bintray.com/content/sild/otus-cpp/homework/0.0.${TRAVIS_BUILD_NUMBER}/${TARGET}-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip_cleanup: true
    local_dir: html
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
