[package]
name = "perf_check"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["real_blackbox"] }

[[bench]]
name = "clone_vs_ref"
harness = false
