[package]
name = "smart_home"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
itertools = "0.11.0"
log = "0.4.20"
tera = "1"
include_dir = "0.7.1"
serde_json = { version = "1.0"}
