[package]
name = "panic_moka"
version = "0.1.0"
edition = "2021"

[dependencies]
moka = { version = "0.12.10", features = ["async-lock", "future"] }
tokio = {version = "1.43.0", features = ["full"]}
anyhow = "1.0.44"
